config/routes.rb
Rails.application.routes.draw do
  resources :port_stocks
  resources :stocks
  resources :portfolios do
    resources :stocks, only: [:index, :new]
  end

  resources :users do
    resources :portfolios
    resources :stocks
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  delete '/portfolios/:portfolio_id/stocks/remove', to: "port_stocks#remove"
  patch '/port_stocks', to: 'port_stocks#update_stock'

  get "/auth/facebook/callback", to: "omniauth_callbacks#facebook"
end

app/models/api.rb
require 'httparty'
class Api
  def self.get_info(ticker)
    response = HTTParty.get("https://www.alphavantage.co/query?function=OVERVIEW&symbol=#{ticker}&apikey=#{ENV['API_KEY']}")
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/port_stock.rb
class PortStock < ApplicationRecord
  belongs_to :portfolio
  belongs_to :stock

  scope :order_by_shares, -> { order(shares: :desc) }

  def symbol
    stock = Stock.find(self.stock_id)
    stock.symbol
  end

  def name
    stock = Stock.find(self.stock_id)
    stock.name
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :user
  has_many :port_stocks, dependent: :destroy
  has_many :stocks, through: :port_stocks
  validates :name, presence: true

end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :port_stocks
  has_many :portfolios, through: :port_stocks
  has_many :port_stocks, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :portfolios
  has_many :stocks
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController

  def facebook
    user = User.find_or_create_by(uid: auth[:uid], provider: auth[:provider])
    if user
      user.password = "facebook_auth"
      session[:user_id] = user.id
      user.save
      redirect_to user_portfolios_path(user)
    end
  end

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/port_stocks_controller.rb
class PortStocksController < ApplicationController
  include UsersHelper


  def create
    create_port_stocks
  end
  def remove
    remove_port_stocks
  end
  def update_stock
    if params[:shares] != ""
      port_stock = PortStock.find(params[:stock_id])
      port_stock.update(shares: params[:shares])
      redirect_to portfolio_stocks_path(params[:port_id].to_i)
    else
      # error
      flash[:notice] = "ERROR: Please enter a value for the amount of shares"
      redirect_to portfolio_stocks_path(params[:port_id].to_i)
    end
  end

  private

  def port_stock_params
    params.values_at(:port_id, :stock_ids)
  end

  def create_port_stocks
    if port_stock_params[0] != nil
      port_stock_params[1].each do |id|
        if !current_user.portfolios.find_by_id(port_stock_params[0].to_i).stocks.include?(Stock.find(id.to_i))
          port_stock = PortStock.create(portfolio_id: port_stock_params[0].to_i, stock_id: id.to_i, shares: 0)
        end
      end
    else
      # error
    end
    redirect_to "/portfolios/#{port_stock_params[0].to_i}/stocks"
  end

  def remove_port_stocks
    portfolio = current_user.portfolios.find(port_stock_params[0].to_i)
    port_stock_params[1].each do |id|
      port_stock = portfolio.port_stocks.find_by(stock_id: id.to_i)
      port_stock.destroy
    end
    redirect_to "/portfolios/#{port_stock_params[0].to_i}/stocks"
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  include UsersHelper
  before_action :require_logged_in

  def index
    @user = current_user
    @portfolios = current_user.portfolios
  end

  def create
    @user_id = new_port_params[1].to_i
    @portfolio = Portfolio.new(name: new_port_params[0], user_id: @user_id)
    if @portfolio.save
      redirect_to user_portfolios_path(@user_id)
    else
      flash[:notice] = @portfolio.errors.full_messages.first
      render :new
    end
  end

  def destroy
    portfolio = current_user.portfolios.find_by_id(destroy_params.to_i)
    if portfolio.destroy
      redirect_to user_portfolios_path(current_user.id)
    else
      # Flash error
    end
  end

  def new
    @user_id = new_port_params[1].to_i
    @portfolio = Portfolio.new
  end

  private
  def new_port_params
    params.values_at(:name, :user_id)
  end
  def destroy_params
    params.fetch(:id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    return redirect_to '/login' if !params[:email] || params[:email].empty?
    user = User.find_by(email: params[:email])
    user = user.try(:authenticate, params[:password])
    return redirect_to '/login' unless user
    session[:user_id] = user.id
    redirect_to user_portfolios_path(user)
  end

  def destroy
    session.delete :user_id
    redirect_to '/login'
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  include UsersHelper

  def new
    @port_id = params[:portfolio_id]
  end

  def index
    @port_id = stock_params[1]
    if user?
      @user = params[:user_id]
      @stocks = current_user.stocks
    else
      @user = nil
      @port_id = stock_params[1]
      @stocks = current_user.portfolios.find(params[:portfolio_id]).port_stocks.order_by_shares
      @user_stocks = current_user.stocks
      @amount = dividend_amount(@stocks)
    end
  end

  def create
    ticker = stock_params[0].upcase
    if !ticker.empty?
      if stock_params[1]
        add_to_list_then_portfolio(ticker, stock_params[1])
        redirect_to portfolio_stocks_path(stock_params[1])
      else
        create_stock(ticker, 1)
        redirect_to user_stocks(current_user)
      end
    else
      # error
    end
  end

  def destroy
    stock = current_user.stocks.find(params[:id])
    stock.destroy
    redirect_to user_stocks_path(current_user)
  end

  private

  def add_to_list_then_portfolio(ticker, port_id)
    create_stock(ticker, 2)
    stock = current_user.stocks.find_by(symbol: ticker)
    PortStock.create(portfolio_id: port_id, stock_id: stock.id, shares: 0)
  end

  def user?
    if params[:user_id]
      return true
    end
    return false
  end

  def dividend_amount(stocks)
    amount = 0
    stocks.each do |s|
      stock = Stock.find(s.stock_id)
      amount += stock.dividend_per_share.to_f * s.shares
    end
    return amount
  end


  def create_stock(ticker, error_code)
    stock_info = Api.get_info(ticker)
    if !current_user.stocks.any? {|x| x.symbol == ticker} && !stock_info.empty?
      stock = Stock.create(:symbol => stock_info['Symbol'], :name => stock_info["Name"], :description => stock_info["Description"], :dividend_per_share => stock_info["DividendPerShare"], :dividend_date => stock_info["DividendDate"], :user_id => current_user.id)
      # redirect_to user_stocks_path(current_user)
    else
      # Print Error
      if error_code == 1
        flash[:notice] = "Error: Stock already exists or ticker is invalid"
      else
        flash[:notice] = "Stock either already exists or is either invalid. If ticker was valid, stock was added to the portfolio."
      end
      # redirect_to user_stocks_path(current_user)
    end
  end

  def stock_params
    params.values_at(:ticker, :portfolio_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to portfolios_path
    else
      # Flash Error
      flash[:notice] = "Error: One or more fields are empty."
      render :new
    end
  end

  private
  def user_params
    # params.require(:user).permit(:email, :password)
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/port_stocks_helper.rb
module PortStocksHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
  def stock_exist?(port_id, stock_id)
    current_user.portfolios.find(port_id).stocks.include?(Stock.find(stock_id))
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user_id
    session[:user_id]
  end

  def current_user
    User.find_by_id(session[:user_id])
  end

  def require_logged_in
    redirect_to '/login' unless current_user_id
  end
end

app/views/layouts/_navbar.html.erb
    <!-- Navbar -->
    <% if current_user %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container-fluid">
  <a class="navbar-brand" href="/users/<%= current_user.id %>/portfolios">Home</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="/users/<%= current_user.id %>/stocks">My Stocks</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/logout">Logout</a>
      </li>
    </ul>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</div>
</nav>
<% end %>
    <!-- End of navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDividendInvestmentTool</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="image-setup">

<%= render 'layouts/navbar'  %>

    <% if flash[:notice] != nil %>
        <div class="container-c alert alert-danger" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>



    <%= yield %>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>

app/views/portfolios/index.html.erb
<div class="page container">
  <section class="list">
    <h1 style="text-align: center;color: lightgreen;">My Portfolios</h1>
  </section>
  <section class="text-center">
    <a href="/users/<%= @user.id %>/portfolios/new" class="btn btn-primary" id="add-btn">Add Portfolio</a>
  </section>
  <section class="list-options text-center">
    <% @portfolios.each do |p| %>
      <%= link_to p.name, portfolio_stocks_path(p), class: "btn option" %>
    <% end %>
  </section>
</div>

app/views/portfolios/new.html.erb
<section class="" id="new-port">
  <h2 style="color: lightgreen;">Please enter a name:</h2><br>
  <%= form_with url: "/users/#{@user_id}/portfolios", method: :post do |form| %>
  <div class="<%= 'field_with_errors' if @portfolio.errors.any? %>">
    <%= form.label "Name:" %>
    <%= form.text_field :name %><br><br>
  </div>
  <%= form.submit "Create", class: "btn btn-custom" %>
  <% end %>

</section>

app/views/stocks/_my_stocks.html.erb
<br>
<%= form_with url: '/stocks', method: :post do |form| %>
  <%= form.label "Please Enter a ticker" %>
  <div class="<%= 'field_with_errors' if flash[:notice] != nil %>">
    <%= form.text_field :ticker %><br>
  </div>
  <%= form.submit "Add Stock", class: "btn btn-custom"%>
<% end %><br>
<% @stocks.each do |s| %>
  <%= form_with url: "/stocks/#{s.id}", method: :delete do |form| %>
  <h3><%= s.symbol %></h3><%= form.submit "Remove", class: "btn btn-danger stock-list-rmv" %><br><br>
  <% end %>
<% end %>

app/views/stocks/_port_stocks.html.erb
<!-- <div class="" id="wrapper"> -->
  <div class="" id="second" class="">
    <div class="">
      <%= form_with url: "/portfolios/#{@port_id}", method: :delete do |form| %>
        <%= form.submit "Delete Portfolio", class: "btn btn-danger delete-portfolio" %>
      <% end %>
      <%= form_with url: new_portfolio_stock_path, method: :get do |form| %>
        <%= form.submit "Add New Stock", class: "btn btn-custom delete-portfolio" %>
      <% end %>
      <button type="button" name="button" class="btn btn-custom" id="add_button" data-bs-toggle="modal" data-bs-target="#addStock">Add Stocks</button>
      <button type="button" name="button" class="btn btn-custom" data-bs-toggle="modal" data-bs-target="#removeStocks">Remove Stocks</button>
      <div class="" id="update">
        <%= form_with url: '/port_stocks', method: :patch do |form| %>
        <%= form.hidden_field :port_id, value: @port_id %>
        <%= form.label "Update a stock!" %><br>
        <%= form.label "Ticker:" %><br>
        <%= form.select :stock_id, options_from_collection_for_select(@stocks, "id", "symbol"), class: "btn btn-primary" %><br>
        <%= form.label "Amount:" %><br>
        <%= form.number_field :shares %>
        <%= form.submit "Update", class: "btn btn-custom" %>
        <% end %>
      </div>
    </div>
    <div class="table text-center my-custom-scrollbar">
                <br>
                  <table class="table table-striped table-bordered border-custom table-dark table-bordered border-custom">
                  <thead>
                  <tr>
                    <th scope="col">Symbol</th>
                    <th scope="col">Name</th>
                    <th scope="col">Shares</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @stocks.each do |stock| %>
                    <tr>
                      <td><%= stock.symbol %></td>
                      <td><%= stock.name %></td>
                      <td id="x"><%= stock.shares %></td>
                    </tr>
                  <% end %>
                  </tbody>
                  </table>
                  </div>
                    <h2 id="amount">Expected Yearly Dividends: $<%= @amount %></h2>
  </div>
<!-- </div> -->



<!-- Add stock Modal -->
<div class="modal fade" id="addStock" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Select all the stocks you wan to add.</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with url: '/port_stocks', method: :post do |form|%>
      <div class="modal-body">
        <% @user_stocks.each do |s| %>
          <% if !stock_exist?(@port_id.to_i, s.id) %>
            <input type="checkbox" name="stock_ids[]" id="<%= s.id %>" value="<%= s.id %>"> <%= s.symbol %><br>
          <% end %>
        <% end %>
        <input type="hidden" name="port_id" value=<%= @port_id %> >
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= form.submit "Add Stocks", class: "btn btn-custom" %>
      </div>
      <% end %>
    </div>
  </div>
</div>


<!-- Remove stock Modal -->
<div class="modal fade" id="removeStocks" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Select all the stocks you want to remove.</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with url: "/portfolios/#{@port_id}/stocks/remove", method: :delete do |form|%>
      <div class="modal-body">
        <% @stocks.each do |s| %>
            <input type="checkbox" name="stock_ids[]" id="<%= s.stock_id %>" value="<%= s.stock_id %>"> <%= s.symbol %><br>
        <% end %>
        <input type="hidden" name="port_id" value=<%= @port_id %> >
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= form.submit "Remove Stocks", class: "btn btn-custom" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/stocks/index.html.erb
<% if @user %>

  <%= render partial: 'stocks/my_stocks' %>

<% else %>

  <%= render partial: 'stocks/port_stocks' %>

<% end %>

app/views/stocks/new.html.erb
<%= form_with url: stocks_path, method: :post do |f| %>
  <%= f.hidden_field :portfolio_id, value: @port_id %>
  <%= f.label "Enter a ticker" %><br>
  <%= f.text_field :ticker%><br>
  <%= f.submit "Add", class: "btn btn-custom" %>
<% end %>

app/views/users/new.html.erb
<%= render partial: 'sessions/options', locals: {url: '/users', sign_up: true, model: @user} %>